### ISSUE TITLE
测试结果

### ISSUE THREAD

**Issue by SSTato** [DDGRCF/YOLOX_OBB#28]
请问73.17的结果是在val上还是test上啊，因为我用你提供的pth测试的map有80多，我不明白是我弄错了还是什么。

**Comment by DDGRCF** [comment]
test上，需要提交到官方测试网站


SSTato ***@***.***> 于2022年8月26日周五 17:33写道：

**Comment by DDGRCF** [comment]
> SSTato ***@***.***> 于2022年8月26日周五 17:33写道：

你这个应该是在val上的

**Comment by SSTato** [comment]
> > SSTato _**@**_.***> 于2022年8月26日周五 17:33写道：
> 
> 你这个应该是在val上的

为什么在val上能这么高，你使用的训练集是自己划分的吗

**Comment by DDGRCF** [comment]
> > > SSTato _**@**_.***> 于2022年8月26日周五 17:33写道：
> > 
> > 
> > 你这个应该是在val上的
> 
> 为什么在val上能这么高，你使用的训练集是自己划分的吗

因为是train，val一起训练的
