### ISSUE TITLE
能给个实例分割的使用教程吗？

### ISSUE THREAD

**Issue by anonymoussss** [DDGRCF/YOLOX_OBB#29]
如题

**Comment by DDGRCF** [comment]
> 如题

今明两天就会更新

**Comment by DDGRCF** [comment]
已经在知乎上更新https://github.com/DDGRCF/YOLOX_OBB/issues/29#issue-1385901379，文章最后面

**Comment by anonymoussss** [comment]
@DDGRCF 
多谢~ 还有个问题，您这个库的backbone是用的yolov5的darknet吗？我看get_model部分和yolov5源码写法是一致的

**Comment by DDGRCF** [comment]
> @DDGRCF 多谢~ 还有个问题，您这个库的backbone是用的yolov5的darknet吗？我看get_model部分和yolov5源码写法是一致的

不是的，还是yolox的，只不过我改成了yolov5的写法，这样方便拓展
