### ISSUE TITLE
yolox.data.DOTADataset

### ISSUE THREAD

**Issue by shenzhangzhou** [DDGRCF/YOLOX_OBB#3]
您好，我在yolox_obb_base.py中看到from yolox.data import DOTADataset，但无法找到DOTADatset，能麻烦提供吗？

**Comment by DDGRCF** [comment]
OK

**Comment by DDGRCF** [comment]
> 您好，我在yolox_obb_base.py中看到from yolox.data import DOTADataset，但无法找到DOTADatset，能麻烦提供吗？

已经更新，有需要可以重新拉取

**Comment by shenzhangzhou** [comment]
> 

好的，这就试试，谢啦。

**Comment by jolt2017** [comment]
你好，你这里是爸  DOTA 数据集，组织成coco 格式 是么？
