### ISSUE TITLE
OOM RuntimeError is raised due to the huge memory cost during label assignment.

### ISSUE THREAD

**Issue by iodncookie** [DDGRCF/YOLOX_OBB#31]
`OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.`

config :
`╒══════════════════╤═══════════════════════════════════════════════════════╕
│ keys             │ values                                                │
╞══════════════════╪═══════════════════════════════════════════════════════╡
│ seed             │ None                                                  │
├──────────────────┼───────────────────────────────────────────────────────┤
│ output_dir       │ 'YOLOX_outputs'                                       │
├──────────────────┼───────────────────────────────────────────────────────┤
│ print_interval   │ 10                                                    │
├──────────────────┼───────────────────────────────────────────────────────┤
│ eval_interval    │ 10                                                    │
├──────────────────┼───────────────────────────────────────────────────────┤
│ modules_config   │ 'configs/modules/yoloxt_obb.yaml'                     │
├──────────────────┼───────────────────────────────────────────────────────┤
│ losses_config    │ 'configs/losses/yolox_losses_obb.yaml'                │
├──────────────────┼───────────────────────────────────────────────────────┤
│ dataset_config   │ 'configs/datasets/my_plate.yaml'                      │
├──────────────────┼───────────────────────────────────────────────────────┤
│ data_num_workers │ 4                                                     │
├──────────────────┼───────────────────────────────────────────────────────┤
│ input_size       │ (416, 416)                                            │
├──────────────────┼───────────────────────────────────────────────────────┤
│ multiscale_range │ 5                                                     │
├──────────────────┼───────────────────────────────────────────────────────┤
│ mosaic_prob      │ 1.0                                                   │
├──────────────────┼───────────────────────────────────────────────────────┤
│ mixup_prob       │ 0.0                                                   │
├──────────────────┼───────────────────────────────────────────────────────┤
│ hsv_prob         │ 1.0                                                   │
├──────────────────┼───────────────────────────────────────────────────────┤
│ flip_prob        │ 0.5                                                   │
├──────────────────┼───────────────────────────────────────────────────────┤
│ degrees          │ 10.0                                                  │
├──────────────────┼───────────────────────────────────────────────────────┤
│ translate        │ 0.1                                                   │
├──────────────────┼───────────────────────────────────────────────────────┤
│ mosaic_scale     │ (0.4, 1.2)                                            │
├──────────────────┼───────────────────────────────────────────────────────┤
│ mixup_scale      │ (0.4, 1.2)                                            │
├──────────────────┼───────────────────────────────────────────────────────┤
│ shear            │ 2.0                                                   │
├──────────────────┼───────────────────────────────────────────────────────┤
│ enable_mixup     │ True                                                  │
├──────────────────┼───────────────────────────────────────────────────────┤
│ warmup_epochs    │ 1                                                     │
├──────────────────┼───────────────────────────────────────────────────────┤
│ max_epoch        │ 300                                                   │
├──────────────────┼───────────────────────────────────────────────────────┤
│ warmup_lr        │ 0                                                     │
├──────────────────┼───────────────────────────────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                                            │
├──────────────────┼───────────────────────────────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'                                        │
├──────────────────┼───────────────────────────────────────────────────────┤
│ no_aug_epochs    │ 3                                                     │
├──────────────────┼───────────────────────────────────────────────────────┤
│ min_lr_ratio     │ 0.05                                                  │
├──────────────────┼───────────────────────────────────────────────────────┤
│ ema              │ True                                                  │
├──────────────────┼───────────────────────────────────────────────────────┤
│ no_eval          │ True                                                  │
├──────────────────┼───────────────────────────────────────────────────────┤
│ weight_decay     │ 0.0005                                                │
├──────────────────┼───────────────────────────────────────────────────────┤
│ momentum         │ 0.9                                                   │
├──────────────────┼───────────────────────────────────────────────────────┤
│ exp_name         │ 'yolox_tiny_plate'                                    │
├──────────────────┼───────────────────────────────────────────────────────┤
│ test_size        │ (1024, 1024)                                          │
├──────────────────┼───────────────────────────────────────────────────────┤
│ postprocess_cfg  │ {'conf_thre': 0.05, 'nms_thre': 0.1}                  │
├──────────────────┼───────────────────────────────────────────────────────┤
│ copy_paste_prob  │ 1.0                                                   │
├──────────────────┼───────────────────────────────────────────────────────┤
│ enable_debug     │ False                                                 │
├──────────────────┼───────────────────────────────────────────────────────┤
│ enable_resample  │ True                                                  │
├──────────────────┼───────────────────────────────────────────────────────┤
│ aug_ignore       │ ['plate']                                             │
├──────────────────┼───────────────────────────────────────────────────────┤
│ empty_ignore     │ False                                                 │
├──────────────────┼───────────────────────────────────────────────────────┤
│ long_wh_thre     │ 6                                                     │
├──────────────────┼───────────────────────────────────────────────────────┤
│ short_wh_thre    │ 3                                                     │
├──────────────────┼───────────────────────────────────────────────────────┤
│ overlaps_thre    │ 0.6                                                   │
├──────────────────┼───────────────────────────────────────────────────────┤
│ evaluate_cfg     │ {'is_merge': False, 'is_submiss': False, 'nproc': 10} │
├──────────────────┼───────────────────────────────────────────────────────┤
│ data_dir         │ '/data/datasets/plate_data/yolox_obb_data'            │
├──────────────────┼───────────────────────────────────────────────────────┤
│ train_ann        │ 'train'                                               │
├──────────────────┼───────────────────────────────────────────────────────┤
│ val_ann          │ 'val'                                                 │
├──────────────────┼───────────────────────────────────────────────────────┤
│ test_ann         │ 'test'                                                │
├──────────────────┼───────────────────────────────────────────────────────┤
│ num_classes      │ 1                                                     │
╘══════════════════╧═══════════════════════════════════════════════════════╛`

how to solve?

**Comment by DDGRCF** [comment]
[https://github.com/Megvii-BaseDetection/YOLOX/issues/117](https://link.zhihu.com/?target=https%3A//github.com/Megvii-BaseDetection/YOLOX/issues/117)
