### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by jolt2017** [DDGRCF/YOLOX_OBB#5]
您好，
   想要训练下您的代码，根据文档数据集搞了好久，请问您这边有个轻量级的数据集，可以直接 train 么？ 下载了 coco128，但是不能直接训练，是需要转换成  dota 格式？

**Comment by DDGRCF** [comment]
> 
如果需要训练其他的数据集，则需要转成dota数据集的形式，然后再根据BboxToolkit的代码裁剪(就算不裁剪，也要如此，因为要导出指定格式).如果你觉得BboxToolkit的使用比较麻烦的，我稍后在my_exps中写一个比较详细的说明.

**Comment by jolt2017** [comment]
> 
好的，谢谢，要是能把 coco、或者 voc 格式转换成 dota 就更好了，毕竟检测任务里这两种格式用的相对多一点，谢谢.

**Comment by jolt2017** [comment]
> > 
> 
> 如果需要训练其他的数据集，则需要转成dota数据集的形式，然后再根据BboxToolkit的代码裁剪(就算不裁剪，也要如此，因为要导出指定格式).如果你觉得BboxToolkit的使用比较麻烦的，我稍后在my_exps中写一个比较详细的说明.

或者,你可以直接把 组织好的dota数据集，传到 百度云，或者 google drive上，这样可以直接用。

**Comment by DDGRCF** [comment]
> 如果需要训练其他的数据集，则需要转成dota数据集的形式，然后再根据BboxToolkit的代码裁剪(就算不裁剪，也要如此，因为要导出指定格式).如果你觉得BboxToolkit的使用比较麻烦的，我稍后在my_exps中写一个比较详细的说明.

后面我会继续完善相关操作

**Comment by jolt2017** [comment]
> > 如果需要训练其他的数据集，则需要转成dota数据集的形式，然后再根据BboxToolkit的代码裁剪(就算不裁剪，也要如此，因为要导出指定格式).如果你觉得BboxToolkit的使用比较麻烦的，我稍后在my_exps中写一个比较详细的说明.
> 
> 后面我会继续完善相关操作

搞了一下午 终于可以训练了...

**Comment by yuxin7** [comment]
> > > 如果需要训练其他的数据集，则需要转成dota数据集的形式，然后再根据BboxToolkit的代码裁剪(就算不裁剪，也要如此，因为要导出指定格式).如果你觉得BboxToolkit的使用比较麻烦的，我稍后在my_exps中写一个比较详细的说明.
> > 
> > 
> > 后面我会继续完善相关操作
> 
> 搞了一下午 终于可以训练了...

您好，我想问一下，您训练的数据集的标注格式和目录是什么样的？
