### ISSUE TITLE
inference err

### ISSUE THREAD

**Issue by jolt2017** [DDGRCF/YOLOX_OBB#6]
![企业微信截图_16391043627685](https://user-images.githubusercontent.com/45425532/145508653-35e2acb1-0e43-4ff9-8b9d-8df7a89acb9f.png)
推理的时候 报这种错误 不知道是怎么回事

**Comment by jolt2017** [comment]
这里主要是 cuda 报错，如果把 参数 --device 改成 cpu 就可以,不知道为啥， setup.py 没安装成功么？

**Comment by DDGRCF** [comment]
> 

我看一应该有个bug，我过会修复一下

**Comment by jolt2017** [comment]
> 

请问修复了么？

**Comment by DDGRCF** [comment]
> > 
> 
> 请问修复了么？

您好，修復了，你可以重新拉取

**Comment by jolt2017** [comment]
> > > 
> > 
> > 
> > 请问修复了么？
> 
> 您好，修復了，你可以重新拉取

好的 谢谢，我有空测下.
