### ISSUE TITLE
能大概说下改了yolox哪些地方吗？

### ISSUE THREAD

**Issue by savage2046** [DDGRCF/YOLOX_OBB#7]
能大概说下改了yolox哪些地方吗？或者提供一下思路。在做个项目，刚好用的上，不胜感激！

**Comment by DDGRCF** [comment]
算法方面，在原来的基础上直接回归一个角度，没有其他地方。
然后在数据增强方面，除了原来的mosaic mixup，还有无标注图片忽略，
对于水平标注的图片不添加旋转和剪切增强，copy-paste增强，
copy-paste增强带有resample，也就是样本数量多的类别少采样，样本数量
少的类别多采样，另外对代码的进行简化，加快训练速度

**Comment by savage2046** [comment]
是否可以回归更多的关键点？比如瓶子的头部和底部。还是说关键点的检测有其它更有效的算法？我想开发一个工业应用，识别流水线上不同型号产品，确定关键点（用于测量长度），有什么好的建议？

**Comment by savage2046** [comment]
有好用的标注软件推荐一下吗？rolabelimg难用到吐了
