### ISSUE TITLE
旋转框确定正样本区域是怎么计算的呢，能说一下思路吗，谢谢了

### ISSUE THREAD

**Issue by lalalagogogochong** [DDGRCF/YOLOX_OBB#9]
![image](https://user-images.githubusercontent.com/44855506/156488949-9da56449-f9c7-410b-b70b-ddcd772f37eb.png)

**Comment by DDGRCF** [comment]
就是通过旋转投影矩阵把到每个anchor point 的距离转化到gt  box的旋转坐标上，也就是相当于坐标变换，你可以在纸上画一画
